homework_count = (12)
hours_count = (1.5)
name_of_course = ('Python')
time_for_task = (1.5 / 12)
print ('Курс:', name_of_course,'всего задач:', homework_count,'затрачено часов:', hours_count,'среднее выполнение задания', time_for_task, 'часа' )
